"use strict";

const cars = [
  { name: "BLT McMuffin", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Tojásos McMuffin", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Tojásos-baconos McMuffin", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Dupla sajtos toast", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Baconös toast", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Fresh McMuffin", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Maestro Tennessee BBQ Brutus hagymakarikával és röstipogácsával", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Dupla Sajtos McRoyal", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Big Mac", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Tripla Cheesy", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Camembertes sajtrudak", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Chicken McNuggets", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Erős Pistás szósz", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Fokhagymás szósz", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "McFlurry M&M's", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Super McFreeze karamellás öntettelsd", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "McCrispy", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "McWrap", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "McWrap sült csirkemellel", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Spicy Chickenburger", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Sertés McFarm", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "Filet-O-Fish", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "McWrap camembertes sajtrudakkal", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "BBQ Burger", img: "src/img/bmw_z1.jpg", origin: "", type: "mcdonald", eaten: "yes" },
  { name: "CHEDDAR CRUNCH BURGER TARTÁR SZÓSSZAL", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "DRAGON BALL Z SAJTGOLYÓ", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "TERIYAKI KATSU SANDO", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "SPICY TERIYAKI KATSU SANDO", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "KLASSZIK & PIKÁNS  KENTUCKY HOT DOG", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "SHAKE DELUXE: TEJKARAMELLÁS", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "DELUXE ICE CREAM - SÓS KARAMELL", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "POKÉ BOWL CALIFORNIA SUN", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "POKÉ BOWL SWEETEST CHILI", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "KENTUCKY GOLD GRANDER", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "ZINGER", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "GRANDER", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "ÉDES CHILI LUNCHBOX", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "KELETI TERIYAKI LUNCHBOX", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "KENTUCKY GOLD WRAPPER", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "TWISTER CLASSIC", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "QURRITO", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "KENTUCKY GOLD FRIES", img: "src/img/bmw_z1.jpg", origin: "", type: "kfc", eaten: "yes" },
  { name: "Truffle Cheese Lover", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "King’s Smoky Grilled", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "King’s Angry Andalouse", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Western Whopper", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Bacon King", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "WHOPPER", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Chicken Truffle Cheese Lover", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Chicken Bacon King", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Chicken Royal", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Deluxe Chicken Wrap", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Smoky Chicken Wrap", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "22-es Dupla Kosár", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Full Fries", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Gouda Sajtfalatok", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Spicy King Nuggets", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Chili Cheese Nuggets", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Baconos-tojásos Szendvics", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Baconos Sajtos Toast", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Sajtos Toast", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Oreo Shake", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Chili Cheese Szósz", img: "src/img/bmw_z1.jpg", origin: "", type: "burgerking", eaten: "yes" },
  { name: "Pulled pork tál", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "Csirkés tál", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "Sajtburger", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "Pulled Pork Szendvics", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "Bitang burger", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "Csirkés szendvics", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "Smash burger", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "Bamba burger", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Monterrey burger", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Big Kahuna burger", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Amerikai sajtburger", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Sloppy Joe burger", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Steakhouse burger (#OKTOGON)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Budapest burger (#BAZILIKA)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Pulled pork burger (#CORVIN)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Pulled Beef burger (#KOLOSY)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Downtown burger (#ÁRKÁD)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Gourmet burger (#FERENCIEK)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Fatburger (#MOSZKVA)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Nachos burger (#WESTEND)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Amazing burger (#ALLEE)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Libamájas burger (#ASTORIA)", img: "src/img/bmw_z1.jpg", origin: "Bamba Marha", type: "burgers", eaten: "yes" },
  { name: "Smoky bros", img: "src/img/bmw_z1.jpg", origin: "The Bros.", type: "burgers", eaten: "yes" },
  { name: "Cheese please", img: "src/img/bmw_z1.jpg", origin: "The Bros.", type: "burgers", eaten: "yes" },
  { name: "Classic fresh burger", img: "src/img/bmw_z1.jpg", origin: "The Bros.", type: "burgers", eaten: "yes" },
  { name: "El fuego", img: "src/img/bmw_z1.jpg", origin: "The Bros.", type: "burgers", eaten: "yes" },
  { name: "Triple Meat", img: "src/img/bmw_z1.jpg", origin: "The Bros.", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
  { name: "asd", img: "src/img/bmw_z1.jpg", origin: "", type: "burgers", eaten: "yes" },
]