"use strict";

const cars = [
  { name: "BMW Z1", img: "src/img/bmw_z1.jpg", origin: "Germany" },
  { name: "BMW E21", img: "src/img/bmw_e21.jpg", origin: "Germany" },
  { name: "BMW E24", img: "src/img/bmw_e24.avif", origin: "Germany" },
  { name: "BMW E30", img: "src/img/bmw_e30_m3.webp", origin: "Germany" },
  { name: "BMW E46", img: "src/img/bmw_e46_m3.jpg", origin: "Germany" },
  { name: "BMW 440i", img: "src/img/bmw_g26_440i.webp", origin: "Germany" },
  { name: "Mercedes 450SL R107", img: "src/img/mercedes_450sl_r107.jpg", origin: "Germany" },
  { name: "Mercedes 300SL R107", img: "src/img/mercedes_sl300_r107.jpg", origin: "Germany" },
  { name: "Mercedes 190 W201", img: "src/img/mercedes_190_w201.jpg", origin: "Germany" },
  { name: "Mercedes EQA 250", img: "src/img/eqa250.jpg", origin: "Germany" },
  { name: "Volkswagen Golf MK II", img: "src/img/vw_golf_mkii.jpg", origin: "Germany" },
  { name: "Audi Quattro S1", img: "src/img/audi_quattro_s1.jpg", origin: "Germany" },
  { name: "Opel Olympia Rekord 1954", img: "src/img/opel_olympia_rekord_54.jpg", origin: "Germany" },
  { name: "Mazda MX-5 Miata", img: "src/img/mazda_mx5_miata.jpg", origin: "Japan" },
  { name: "Mitsubishi 3000 GT", img: "src/img/mitsu_3000gt.webp", origin: "Japan" },
  { name: "Mitsubishi Lancer evo VII", img: "src/img/mitsu_lancer_evo_VII.webp", origin: "Japan" },
  { name: "Mitsubishi Galant 2.5 V6", img: "src/img/mitsu_galant_vr4.jpg", origin: "Japan" },
  { name: "Nissan Skyline R34", img: "src/img/niss_skyline_r34.jpg", origin: "Japan" },
  { name: "Nissan Silvia S15", img: "src/img/nissan_silvia_s15.jpg", origin: "Japan" },
  { name: "Subaru WRX STI", img: "src/img/subaru_wrx_sti_2014.jpg", origin: "Japan" },
  { name: "Toyota Corolla Levin AE86", img: "src/img/toyota_AE86.jpg", origin: "Japan" },
  { name: "Toyota Supra MK4", img: "src/img/toyota_supra_mk4.jpg", origin: "Japan" },
  { name: "Buick Skylark 1972", img: "src/img/buick_skylark_72.jpg", origin: "USA" },
  { name: "Cadillac Eldorado 1959", img: "src/img/cadillac_eldorado_59.jpg", origin: "USA" },
  { name: "Cadillac DeVille 1965", img: "src/img/cadillac_deville_65.avif", origin: "USA" },
  { name: "Cadillac Eldorado 1970", img: "src/img/cadillac_eldorado_70.jpg", origin: "USA" },
  { name: "Chevrolet Chevelle 1971", img: "src/img/chevrolet_chevelle_71.jpg", origin: "USA" },
  { name: "Chevrolet Monte Carlo 1975", img: "src/img/chevrolet_monte_carlo_75.webp", origin: "USA" },
  { name: "DeLorean DMC-12", img: "src/img/delorean_dmc12.png", origin: "USA" },
  { name: "Dodge Challenger Hellcat Redeye", img: "src/img/dodge_challenger_hellc_redeye.webp", origin: "USA" },
  { name: "Dodge Charger", img: "src/img/dodge_charger_srt.jpg", origin: "USA" },
  { name: "Excalibur Phateon", img: "src/img/excalibur_phateon.jpg", origin: "USA" },
  { name: "Ford Mustang 1965", img: "src/img/ford_mustang_1965.jpg", origin: "USA" },
  { name: "Ford GT40", img: "src/img/ford_gt40.jpg", origin: "UK" },
  { name: "Lincoln Continental 1975", img: "src/img/lincoln_continental_75.jpg", origin: "USA" },
  { name: "Mercury Montrey 1972", img: "src/img/mercury_montrey_72.jpg", origin: "USA" },
  { name: "Pontiac Firebird 1977", img: "src/img/pontiac_firebird.webp", origin: "USA" },
  { name: "Ferrari F40", img: "src/img/ferrari_f40.jpg", origin: "Italy" },
  { name: "Maserati Quattroporte VI", img: "src/img/maserati_quattroporte_2018.avif", origin: "Italy" },
  { name: "Citroën DS 21 Pallas", img: "src/img/citroen_pallas_ds21.webp", origin: "France" },
  { name: "Volga GAZ-24", img: "src/img/volga_gaz24.jpg", origin: "Russia" },
  { name: "Lada Niva 4x4", img: "src/img/lada_niva_4x4.jpg", origin: "Russia" },
  { name: "Lada VAZ-2107", img: "src/img/lada_2107.jpg", origin: "Russia" },
];